// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Golawala",
  category: "Dessert shop",
  address: "\nScience City Rd, Hebatpur, Ahmedabad, Gujarat 380060",
  phone: "\n073833 21075",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/Golawala/@23.0785841,72.5034475,17z/data=!3m1!4b1!4m6!3m5!1s0x395e9db0dccdd4eb:0x316f6751ad53eeb7!8m2!3d23.0785841!4d72.5034475!16s%2Fg%2F11m6zgm9tf?entry=ttu&g_ep=EgoyMDI2MDUyNS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0785841",
  longitude: "72.5034475",
  rating: "",
  reviewsCount: "102",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1779966436539_0.jpg", "/images/gmap_1779966436740_1.jpg", "/images/gmap_1779966437016_2.jpg", "/images/gmap_1779966437306_3.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Sweet Delights on Science City Rd",
  heroDescription: "Indulge in the rich flavors of Ahmedabad at Golawala, located on Science City Rd, Hebatpur. Our dessert shop offers a wide range of unique treats that blend traditional and modern flavors. From creamy pastries to decadent chocolates, every bite is a delight.",
  aboutTitle: "The Story of Golawala",
  aboutText: "Golawala is nestled in the heart of Ahmedabad, on Science City Rd, Hebatpur, where the vibrant energy of the city meets the sweetness of our desserts. Our team of skilled pastry chefs and bakers work tirelessly to create innovative and delicious treats that cater to the diverse tastes of our customers. With a focus on using only the finest ingredients and traditional cooking methods, we aim to provide an unparalleled dessert experience that leaves you wanting more.",
  services: [
    { icon: "🍰", title: "Custom Cake Design", description: "Get a custom cake designed for your special occasion, starting from ₹845" },
    { icon: "🍫", title: "Chocolate Making Workshop", description: "Learn the art of chocolate making with our expert chefs, priced at ₹1357 per person" },
    { icon: "🎂", title: "Birthday Party Packages", description: "Celebrate your birthday with our special party packages, starting from ₹2100" },
    { icon: "🥧", title: "Pastry of the Month Club", description: "Subscribe to our monthly pastry club and get a new dessert every month, priced at ₹560" },
    { icon: "🍦", title: "Ice Cream Tasting Experience", description: "Indulge in a unique ice cream tasting experience, priced at ₹945 per person" },
    { icon: "🎁", title: "Dessert Gift Boxes", description: "Send a thoughtful gift to your loved ones with our dessert gift boxes, starting from ₹1250" }
  ],
  whyChooseUs: [
    { icon: "🏆", title: "Unique Flavor Combinations", description: "Our team of expert chefs create unique and delicious flavor combinations that you won't find anywhere else" },
    { icon: "🌟", title: "High-Quality Ingredients", description: "We use only the finest ingredients to ensure that every bite is a delight" },
    { icon: "👥", title: "Personalized Service", description: "Our friendly staff will help you choose the perfect dessert for your occasion" },
    { icon: "🎉", title: "Special Occasion Expertise", description: "We specialize in creating customized desserts for special occasions like birthdays, weddings, and anniversaries" }
  ],
  testimonials: [
    { name: "Hridaya Mehta", role: "Regular Customer", text: "I've been a regular customer at Golawala for months now, and I must say that their custom cake design service is top-notch. The team is very friendly and helpful, and the cakes are always delicious.", rating: 5 },
    { name: "Himanshu Patel", role: "Birthday Boy", text: "I had my birthday party at Golawala, and it was an unforgettable experience. The birthday party package was very reasonably priced, and the staff took care of every detail.", rating: 5 },
    { name: "Harshita Desai", role: "Food Blogger", text: "I recently visited Golawala to try their pastry of the month club, and I was blown away by the variety and quality of the pastries. The subscription service is very convenient, and the prices are very competitive.", rating: 5 }
  ],
  faq: { items: [{ question: "What is the price range of your custom cakes?", answer: "Our custom cakes start from ₹845 and can go up to ₹2707, depending on the design and size" },
    { question: "Do you offer any discounts for bulk orders?", answer: "Yes, we offer discounts for bulk orders. Please contact us for more information" },
    { question: "Can I customize my dessert gift box?", answer: "Yes, you can customize your dessert gift box with your choice of desserts and packaging" },
    { question: "How do I subscribe to the pastry of the month club?", answer: "You can subscribe to our pastry of the month club by visiting our website or by contacting us directly" },
    { question: "What is the cancellation policy for birthday party packages?", answer: "Please contact us for more information on our cancellation policy" },
    { question: "Do you offer any vegan or gluten-free options?", answer: "Yes, we offer a variety of vegan and gluten-free options. Please contact us for more information" }] },
  ctaTitle: "Indulge in the Sweet Life",
  ctaDescription: "Visit us today and discover the sweet delights of Golawala. Our friendly staff will be happy to help you choose the perfect dessert for your occasion.",
  ctaButtonText: "Explore Now",
  metaDescription: "Golawala dessert shop on Science City Rd, Hebatpur, Ahmedabad",
};

export const siteConfig = {
  layout: "scandinavian",
  theme: "elegant",
  sections: ["testimonials", "faq", "gallery", "contact", "about", "services"],
  heroVariant: "fullscreen-cinematic",
  navStyle: "floating-pill",
  animationStyle: "scale-in-bounce",
  cardStyle: "rounded-xl bg-gradient-to-br from-card to-transparent",
  darkMode: false,
};
