// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Golawala",
  category: "Dessert shop",
  address: "\nScience City Rd, Hebatpur, Ahmedabad, Gujarat 380060",
  phone: "\n073833 21075",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/Golawala/@23.0785841,72.5034475,17z/data=!3m1!4b1!4m6!3m5!1s0x395e9db0dccdd4eb:0x316f6751ad53eeb7!8m2!3d23.0785841!4d72.5034475!16s%2Fg%2F11m6zgm9tf?entry=ttu&g_ep=EgoyMDI2MDUyNS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0785841",
  longitude: "72.5034475",
  rating: "",
  reviewsCount: "102",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1779967926424_0.jpg", "/images/gmap_1779967926538_1.jpg", "/images/gmap_1779967926876_2.jpg", "/images/gmap_1779967927183_3.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Sweet Delights at Science City",
  heroDescription: "Indulge in the rich flavors of Golawala, Ahmedabad's premier dessert shop, located on Science City Rd, Hebatpur. Our expert chefs craft unique desserts that will tantalize your taste buds. Visit us today and experience the sweetest side of Ahmedabad!",
  aboutTitle: "The Sweet Story of Golawala",
  aboutText: "Nestled in the heart of Ahmedabad, on Science City Rd, Golawala is a dessert lover's paradise. Our shop is designed to provide a warm and welcoming atmosphere, perfect for enjoying a sweet treat. With a passion for innovation and quality, we strive to create desserts that are both delicious and visually stunning. Our team of skilled chefs and friendly staff are dedicated to making your visit to Golawala an unforgettable experience.",
  services: [
    { icon: "🍦", title: "Custom Cakes", description: "Order bespoke cakes for special occasions, starting from ₹857" },
    { icon: "🎂", title: "Dessert Platters", description: "Indulge in our selection of sweet treats, priced at ₹1421 for a platter of 12 pieces" },
    { icon: "🍫", title: "Chocolate Making Workshops", description: "Learn the art of chocolate making with our expert chefs, priced at ₹2174 per session" },
    { icon: "🍮", title: "Ice Cream Subscription", description: "Enjoy a monthly delivery of unique ice cream flavors, starting from ₹357" },
    { icon: "🥧", title: "Pastry of the Month", description: "Savor a new pastry every month, priced at ₹612" },
    { icon: "🍪", title: "Cookie Decorating", description: "Get creative with our cookie decorating sessions, priced at ₹983" }
  ],
  whyChooseUs: [
    { icon: "🌟", title: "Unique Flavor Profiles", description: "Our expert chefs craft one-of-a-kind desserts that will tantalize your taste buds" },
    { icon: "🏙️", title: "Prime Location", description: "Conveniently located on Science City Rd, making it easy to visit us" },
    { icon: "👨‍🍳", title: "Experienced Chefs", description: "Our team of skilled chefs have years of experience in creating delicious desserts" },
    { icon: "📦", title: "Flexible Delivery Options", description: "We offer convenient delivery options to ensure you can enjoy our desserts from the comfort of your own home" }
  ],
  testimonials: [
    { name: "Harrison Patel", role: "Regular Customer", text: "I've been visiting Golawala for months now, and their custom cakes are always a hit at parties. The team is friendly and accommodating, and the prices are very reasonable. I recently ordered a dessert platter for a birthday celebration, and it was a huge success!", rating: 5 },
    { name: "Himanshu Mehta", role: "Food Critic", text: "Golawala's chocolate making workshops are a must-try for any chocolate lover. The instructors are knowledgeable and patient, and the end result is a delicious and unique chocolate creation. I also appreciated the variety of flavors they offer, including some unique and exotic options.", rating: 5 },
    { name: "Hema Deshpande", role: "Event Planner", text: "I recently ordered a pastry of the month subscription for a corporate event, and it was a huge hit with our clients. The pastries were delicious and beautifully presented, and the team at Golawala was a pleasure to work with. I also appreciated the flexibility of their delivery options, which made it easy to plan the event.", rating: 5 }
  ],
  faq: { items: [{ question: "What types of desserts do you offer?", answer: "We offer a wide range of desserts, including custom cakes, dessert platters, ice cream, pastries, and more. Our menu is constantly evolving, so be sure to check our website or visit us in store for the latest offerings." },
    { question: "Do you offer delivery?", answer: "Yes, we offer convenient delivery options to ensure you can enjoy our desserts from the comfort of your own home. Simply place your order online or over the phone, and we'll take care of the rest." },
    { question: "Can I customize my order?", answer: "Yes, we offer customization options for many of our desserts. Simply contact us to discuss your needs, and we'll do our best to accommodate your requests." },
    { question: "What is the price range of your desserts?", answer: "Our prices vary depending on the dessert, but you can expect to pay between ₹357 and ₹2724 for most items. We also offer discounts for bulk orders and loyalty rewards for frequent customers." },
    { question: "Do you offer any discounts or promotions?", answer: "Yes, we regularly offer discounts and promotions to our customers. Follow us on social media or sign up for our email newsletter to stay up-to-date on the latest deals and offers." },
    { question: "How do I contact Golawala?", answer: "You can contact us by phone at 073833 21075, or by visiting our website and filling out the contact form. We're always happy to hear from our customers and look forward to serving you." }] },
  ctaTitle: "Indulge in the Sweet Life",
  ctaDescription: "Visit Golawala today and discover a world of delicious desserts. From custom cakes to chocolate making workshops, we have something for every sweet tooth.",
  ctaButtonText: "Order Now",
  metaDescription: "Golawala: Ahmedabad's premier dessert shop",
};

export const siteConfig = {
  layout: "scandinavian",
  theme: "elegant",
  sections: ["testimonials", "faq", "gallery", "contact", "about", "services"],
  heroVariant: "fullscreen-cinematic",
  navStyle: "floating-pill",
  animationStyle: "scale-in-bounce",
  cardStyle: "rounded-xl bg-gradient-to-br from-card to-transparent",
  darkMode: false,
};
